image:
  repository: dkrinitsyn/agents-infra-test-gateway
  pullPolicy: Always
  tag: "20260403185913"

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: testapp.local
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

env:
  BACKEND_URL: "http://agents-infra-test-backend.agents-infra-test.svc.cluster.local"

namespace: agents-infra-test