apiVersion: v1
kind: Service
metadata:
  name: agents-infra-test-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: agents-infra-test-gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}