image:
  repository: dkrinitsyn/agents-infra-test-backend
  pullPolicy: Always
  tag: "20260425113057"

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

namespace: agents-infra-test